linux-kernel-labs/linux

- Documentation/teaching/index.rst
- Documentation/teaching/lectures/smp.rst
Signed-off-by: Octavian Purdila <tavi@cs.pub.ro>
> Documentation: teaching: add smp lecture

- Documentation/teaching/lectures/interrupts.rst
Corrected some minor errors in interrupts.rst.
Signed-off-by: Robert Baronescu <baronescu.robert@gmail.com>
> Documentation: teaching: lectures: interrupts.rst

- Documentation/teaching/labs/interrupts.rst
> Documentation: teaching: labs: interrupts.rst typos and errors correction

- Documentation/teaching/labs/kernel_modules.rst
Signed-off-by: Anda Nicolae <nicolae.anda@gmail.com>
> lab02: kernel_modules: Add extra exercises

- tools/labs/.gitignore
- tools/labs/templates/filesystems/minfs/kernel/minfs.c
- tools/labs/templates/filesystems/minfs/kernel/minfs.h
- tools/labs/templates/filesystems/minfs/user/mkfs.minfs.c
- tools/labs/templates/filesystems/minfs/user/test-minfs-0.sh
- tools/labs/templates/filesystems/minfs/user/test-minfs-1.sh
- tools/labs/templates/filesystems/minfs/user/test-minfs-2.sh
- tools/labs/templates/filesystems/myfs/myfs.c
- tools/labs/templates/filesystems/myfs/test-myfs-1.sh
- tools/labs/templates/filesystems/myfs/test-myfs-2.sh
I added the second part of the filesystem labs in the same template as part 1.
For the second part, the implementation will start at TODO 5 (I skipped TODO 4 in myfs.c so we can have the same starting number for both of them).
> labs: lab09: add filesystem part2 lab template

- tools/labs/templates/assignments/6-e100/Kbuild
- tools/labs/templates/assignments/6-e100/_checker
- tools/labs/templates/assignments/6-e100/e100-ix.c
- tools/labs/templates/assignments/6-e100/e100-ix.h
One can use this skeleton to start implementing e100 driver
assignment.
Signed-off-by: Daniel Baluta <daniel.baluta@gmail.com>
> tools: labs: assignments: Add ix-e100 driver skeleton

- tools/labs/qemu/Makefile
Signed-off-by: Daniel Baluta <daniel.baluta@gmail.com>
> tools: labs: Fix second tap interface

- tools/labs/qemu/Makefile
- tools/labs/qemu/create_net.sh
Signed-off-by: Daniel Baluta <daniel.baluta@gmail.com>
> tools: labs: qemu: Start nttcp at boot

- Documentation/teaching/labs/device_drivers.rst
> tools: labs: device_drivers: Fix typo

- Documentation/teaching/labs/kernel_api.rst
> Fix Typo in Kernel API lab

- Documentation/teaching/lectures/syscalls.rst
Mostly testing PR creating.
But I also found some `then` typos in syscall lecture :)
> Small typo in syscall lecture

- Documentation/teaching/labs/kernel_api.rst
> Fix typos in kernel api lab

- Documentation/teaching/labs/device_drivers.rst
> teaching: device_drivers: Multiple fixes

- Documentation/teaching/labs/device_drivers.rst
> teaching: labs: device_drivers: content fixes

- Documentation/teaching/labs/interrupts.rst
> teaching: labs: interrupts: Fix content

- tools/labs/Makefile
- tools/labs/qemu/Makefile
Make style updates to `Makefile` files in `tools/labs`.
> tools:labs: Update Makefile

- tools/labs/templates/assignments/0-list/checker/_checker
> Documentation: tools: labs: Fix identation in checker for assignment 0-list

- Documentation/teaching/labs/filesystems_part2.rst
> teaching: labs: filesystems_part2: fix exercise

- Documentation/teaching/labs/device_drivers.rst
> teaching: labs: device_drivers: Fix typo

- Documentation/teaching/labs/filesystems_part1.rst
> Documentation: teaching: labs: filesystems_part1: Fix minor typos

- Documentation/teaching/labs/filesystems_part2.rst
> Documentation: teaching: labs: filesystems_part2: Fix typos

- Documentation/teaching/labs/filesystems_part2.rst
- tools/labs/templates/filesystems/minfs/kernel/minfs.c
This is a code skeleton and contents review for lab09: Filesystems (part 2).
> Review lab09: Filesystems (part 2)

- Documentation/teaching/index.rst
- Documentation/teaching/labs/device_drivers.rst
- Documentation/teaching/labs/networking.rst
> Documentation: teaching: labs: networking: Add networking lab

- Documentation/teaching/labs/networking.rst
- tools/labs/templates/networking/3-4-tcp-sock/tcp_sock.c
- tools/labs/templates/networking/5-udp-sock/test-5.sh
I have missed a couple of review snippets from @valx90. I have fixed the content in this pull request.
> Documentation: teaching: labs: networking: Minor content fixes

- tools/labs/templates/assignments/1-tracer/checker/Makefile
- tools/labs/templates/assignments/1-tracer/checker/README
- tools/labs/templates/assignments/1-tracer/checker/_helper/Kbuild
- tools/labs/templates/assignments/1-tracer/checker/_test/Makefile
Improve `README` and remove `Makefile` errors when building.
> tools/labs/assignments: Refactor checker build infrastructure for 1-tracer

- Documentation/teaching/labs/networking.rst
- tools/labs/templates/networking/1-2-netfilter/kernel/filter.c
- tools/labs/templates/networking/3-4-tcp-sock/Kbuild
- tools/labs/templates/networking/3-4-tcp-sock/tcp_sock.c
- tools/labs/templates/networking/5-udp-sock/Kbuild
- tools/labs/templates/networking/5-udp-sock/udp_sock.c
Update source code for networking lab (update to kernel 4.19). Update contents for networking lab (rewording and formatting).
> tools: labs: Update networking lab (#10)

- Documentation/teaching/lectures/intro.rst
- Documentation/teaching/lectures/so2.cs.pub.ro.rst
> Update 2020 cs.pub.ro team and fix a few intro slides titles

- Documentation/teaching/labs/exercises-summary.hrst
- Documentation/teaching/labs/introduction.rst
- Documentation/teaching/labs/kernel_modules.rst
- tools/labs/qemu/Makefile
- tools/labs/templates/kernel_modules/1-2-test-mod/Kbuild
> Documentation: teaching: labs: kernel_modules exercises updates

- Documentation/teaching/labs/introduction.rst
- Documentation/teaching/labs/kernel_modules.rst
> Documentation: teaching: labs: kernel_modules: add missing KDB section

- Documentation/teaching/labs/block_device_drivers.rst
- Documentation/teaching/labs/deferred_work.rst
- Documentation/teaching/labs/device_drivers.rst
- Documentation/teaching/labs/device_model.rst
- Documentation/teaching/labs/exercises-summary.hrst
- Documentation/teaching/labs/filesystems_part1.rst
- Documentation/teaching/labs/filesystems_part2.rst
- Documentation/teaching/labs/interrupts.rst
- Documentation/teaching/labs/introduction.rst
- Documentation/teaching/labs/kernel_api.rst
- Documentation/teaching/labs/kernel_modules.rst
- Documentation/teaching/labs/memory_mapping.rst
- Documentation/teaching/labs/networking.rst
Add warning to do a git pull before the exercises in every lab.
> Documentation: teaching: labs: Add git pull warning before exercises

- Documentation/teaching/labs/kernel_api.rst
- tools/labs/templates/kernel_api/6-list-sync/list-sync.c
Modify the TODOs in list-sync as follows: TODO 1 to solve exercise 6-list-sync and TODO 2 to solve exercise 7-test-list.
> tools/labs: Add TODO for exercise 7-list-test

- Documentation/teaching/labs/device_drivers.rst
- tools/labs/templates/device_drivers/kernel/so2_cdev.c
> Documentation: labs: device_drivers: update exercises

- Documentation/teaching/labs/deferred_work.rst
Fixed some mistakes in example code (structure -> struct, incorrect variable, missing ampersand)
> Documentation: teaching: labs: deferred_work: Fix example code

- Documentation/teaching/labs/device_drivers.rst
The user-space testing program already has the required operations implemented.
> Documentation: labs: device_drivers: Update extra exercises testing

- Documentation/teaching/info/contributing.rst
Signed-off-by: SeongJae Park <sj38.park@gmail.com>
> docs/contributing: Fix typos: s/linux-lernel/linux-kernel/

- tools/labs/templates/assignments/0-list/list.c
> Fix typo at MODULE_AUTHOR

- Documentation/teaching/lectures/interrupts.rst
Signed-off-by: Octavian Purdila <tavi@cs.pub.ro>
> Documentation: teaching: interrupts: add more details

- Documentation/teaching/lectures/smp.rst
Single-commit version of https://github.com/linux-kernel-labs/linux/pull/169
> Fix typo simple barrier 

- Documentation/teaching/labs/block_device_drivers.rst
> Documentation: teaching: labs: block_device_drivers: Update exercises

- Documentation/teaching/labs/memory_mapping.rst
- Change TODO numbering to match code template
- Fix and improve testing instructions
> documentation: memory_mapping: Fix TODO numbering

- Documentation/teaching/labs/device_drivers.rst
This PR fixes some trivial nits in the 'Character device drivers' lab.
> device_drivers: Fix nits

- Documentation/teaching/labs/deferred_work.rst
- tools/labs/templates/deferred_work/3-4-5-deferred/kernel/deferred.c
This PR fixes trivial nits in 'Deferred work' lab.
> Deferred work: Fix nits

- Documentation/teaching/labs/block_device_drivers.rst
- tools/labs/templates/block_device_drivers/1-2-3-6-ram-disk/kernel/ram-disk.c
- tools/labs/templates/block_device_drivers/1-2-3-6-ram-disk/user/ram-disk-test.c
- tools/labs/templates/block_device_drivers/4-5-relay-disk/test-relay-disk
This PR fixes trivial problems in 'Block device drivers' lab.
> Fix block device drivers

- Documentation/teaching/labs/filesystems_part1.rst
- Documentation/teaching/labs/filesystems_part2.rst
- tools/labs/templates/filesystems/minfs/kernel/minfs.c
- tools/labs/templates/filesystems/myfs/test-myfs-2.sh
- tools/labs/templates/filesystems/myfs/test-myfs.sh
This commit improves 'filesystems part1' by fixing trivial problems.
> filesystems: Fix trivial problems

- Documentation/teaching/labs/networking.rst
This PR fixes a few nits in the networking section.
> Fix networking

- Documentation/teaching/lectures/smp.rst
Signed-off-by: Vincenzo Petrolo <vincenzo@kernel-space.org>
> documentation/smp: Fix typo

- Documentation/teaching/index.rst
- Documentation/teaching/labs/introduction.rst
- Documentation/teaching/labs/kernel_modules.rst
- Documentation/teaching/so2/index.rst
- Documentation/teaching/so2/lab1-intro.rst
- Documentation/userspace-api/media/Makefile
Create SO2 Lab 01 from introduction and kernel_modules labs
Signed-off-by: Valentin Ghita <valx92@gmail.com>
> documentation: labs: create SO2 lab1

- Documentation/teaching/info/vm.rst
- Documentation/teaching/labs/interrupts.rst
- Documentation/teaching/labs/introduction.rst
> Change QEMU_DISPLAY from sdl to gtk

- .github/workflows/main.yml
- Documentation/conf.py
- Documentation/sphinx/ditaa.py
- tools/labs/docker/docs/Dockerfile
Update docker files to use ubuntu-20.04. Update ditaa and conf.py hieroglyph checks to python3 since python2 is no longer supported.
Fixes #235
> Update docker base image to ubuntu-20.04

- Documentation/teaching/index.rst
- Documentation/teaching/info/extra-vm.rst
- Documentation/teaching/info/vm.rst
Do formatting updates and simplifications to virtual machine setup page.
> Simplify and improve formatting on virtual machine setup page

- Documentation/teaching/so2/assign0-kernel-api.rst
- Documentation/teaching/so2/index.rst
The statement of assignment 0 is ported from ocw to kernel linux labs and the content is translated to English.
> Port assignment 0 from ocw to kernel linux labs

- Documentation/teaching/so2/assign1-kprobe-based-tracer.rst
- Documentation/teaching/so2/index.rst
The statement of assignment 1 is ported from ocw to Linux kernel labs and the content is translated to English.
> Port assignment 1 from ocw to Linux kernel labs

- tools/labs/docker/docker-compose.yml
Make it so applications run in the container can display GUI.
> docker: Add support for running GUI applications

- Documentation/teaching/so2/assign1-kprobe-based-tracer.rst
Add homework generation hint for lazy people.
> Add homework generation hint

- Documentation/teaching/labs/block_device_drivers.rst
- tools/labs/templates/block_device_drivers/1-2-3-6-ram-disk/kernel/ram-disk.c
The block devices queues API has changed since the previous versions. Update the documentation and skeleton accordingly.
Signed-off-by: Valentin Ghita <valx92@gmail.com>
Resolves #260.
> Documentation: labs: block_device_drivers: updates for blk-mq

- tools/labs/Makefile
I think it's better not to delete your homework and labs.
At least ask me, "Are you sure you're so stupid?"
> Labs: Makefile: Add prompt for confirmation in make clean skels.

- Documentation/teaching/labs/filesystems_part1.rst
- Documentation/teaching/so2/lab8-filesystems-part1.rst
Add a section in the filesystems-part1 lab (lab8) for the students to
complete the teaching survey created by the computer department.
Signed-off-by: Laurentiu Stefan <steflaurentiu@gmail.com>
> Documentation: so2: Add survey section in the filesystems-part1 lab

- Documentation/teaching/so2/assign3-software-raid.rst
- Documentation/teaching/so2/index.rst
Add SO2 assigment 3. Original is at:
https://ocw.cs.pub.ro/courses/so2/teme/tema3
The assignment requests to create a software RAID1 kernel module.
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
> Documentation: Add the documentation for assignment 3

- Documentation/teaching/so2/assign-chall-pitix.rst
- Documentation/teaching/so2/index.rst
Add assignment statement, testing information and tips. Add link to assignment in SO2 index page.
> Documentation: teaching: Add page for PITIX filesystem assignment

- Documentation/teaching/so2/assign4-transport-protocol.rst
- Documentation/teaching/so2/index.rst
Add rST page for STP (*SO2 Transport Protocol*) assignment.
> Documentation: teaching: Add page for SO2 Transport Protocol assignment

- tools/labs/qemu/Makefile
- tools/labs/qemu/prepare-image.sh
This is in preparation for ARM kernel development lab. The platform using for practice is i.MX6UL.
> tools: labs: qemu: Prepare support for our first ARM platform: i.MX6UL

- Documentation/teaching/labs/filesystems_part2.rst
> fixed typo

- Documentation/teaching/labs/networking.rst
Fixes the typo in word "tipically" to "typically".
> Fix typo in networking.rst

- Documentation/teaching/so2/assign4.c-kvm-vmm.rst
- tools/labs/templates/assignments/7-kvm-vmm/skel/Makefile
- tools/labs/templates/assignments/7-kvm-vmm/skel/guest_16_bits/guest.ld
- tools/labs/templates/assignments/7-kvm-vmm/skel/guest_16_bits/guest16.s
- tools/labs/templates/assignments/7-kvm-vmm/skel/guest_32_bits/guest_code.c
- tools/labs/templates/assignments/7-kvm-vmm/skel/include/device.h
- tools/labs/templates/assignments/7-kvm-vmm/skel/include/queue.h
- tools/labs/templates/assignments/7-kvm-vmm/skel/include/vcpu.h
- tools/labs/templates/assignments/7-kvm-vmm/skel/include/vm.h
- tools/labs/templates/assignments/7-kvm-vmm/skel/payload.ld
- tools/labs/templates/assignments/7-kvm-vmm/skel/vmm.c
We introduce a Virtual Machine Manager based on KVM as homework 7.
Signed-off-by: Alexandru Cihodaru cihodar@amazon.com
Signed-off-by: Radu Iliescu riliescu@amazon.com
Signed-off-by: Vlad Badoiu vlad_andrei.badoiu@upb.ro
> Introduce assignment 7: KVM VMM

- Documentation/teaching/lectures/syscalls.rst
Fix the [system call table](https://linux-kernel-labs.github.io/refs/heads/master/so2/lec2-syscalls.html#system-call-table) in the syscalls lecture.
> Documentation: Syscalls: Fix system call table

- Documentation/teaching/so2/assign2-driver-uart.rst
* Update deadline for 2023
* Update links
> Documentation: assign2: Update 2-uart docs

- Documentation/teaching/so2/assign3-software-raid.rst
* Update deadline for 2023
* Update links
> Documentation: assign3: Update 3-raid docs

- Documentation/teaching/labs/kernel_profiling.rst
Use dates for feedback form for the 2022-2023 semester.
> Doc/teaching/kern_prof: Update information on feedback

- Documentation/teaching/info/vm.rst
- Documentation/teaching/labs/exercises-summary.hrst
- Documentation/teaching/labs/kernel_modules.rst
- Documentation/teaching/so2/lab1-intro.rst
* Add reference to so2-labs gitlab repo
* Change `make boot` to `make console`
> Update documentation for lab1

- Documentation/teaching/lectures/processes.rst
> Documentation: fix grammar in lectures/processes.rst

- Documentation/teaching/lectures/debugging.rst
I am not sure if minor typo fix is welcomed. If not, I will reduce the frequency of typo fix commits. 🙏
> Documentation: lectures: Debugging: Fix typo
