linux-kernel-labs/linux

.circleci/config.yml
Add Circle CI docs builder and publisher for generated html docs to https://linux-kernel-labs.github.io/. 
Building and publishing is done for both for pull requests and branches (after merges). 
The html docs are published under a <branch_name> directory, e.g. 
* https://linux-kernel-labs.github.io/master 
* https://linux-kernel-labs.github.io/pull/77
=> Add docs building and publishing support via Circle CI 

Documentation/teaching/conf.py, Documentation/teaching/labs/conf.py
=> Documentation: move teaching/labs/conf.py to teaching/

Documentation/teaching/lectures/syscalls.rst
Fix the "System Call Flow Summary" slide to fit by rephrasing some
bullets which should also hopefully make some points more clear.
Signed-off-by: Octavian Purdila <tavi@cs.pub.ro>
=> Documentation: teaching: syscall lecture: fix slide to fit

Documentation/teaching/lectures/intro.rst
Corrected some minor typos in intro.rst.
Signed-off-by: Robert Baronescu <baronescu.robert@gmail.com>
=> Documentation: teaching: lectures: intro.rst: Corrected minor typos

Documentation/teaching/lectures/syscalls.rst
Corrected some minor typos in syscalls.rst
Signed-off-by: Robert Baronescu <baronescu.robert@gmail.com>
=> Documentation: teaching: lectures: syscalls.rst: Corrected minor typos

tools/labs/templates/device_drivers/kernel/so2_cdev.c
Exercise 7 (ioctl operations) should have TODO 6 and extra exercises should have TODO 7.
=> lab04: exercises: Fix TODO numbers.

tools/labs/templates/device_drivers/kernel/so2_cdev.c
Since the exchange value in atomic_cmpxchg is set to 1, atomic_inc will not reset it, and so, the resource will be busy at any second call. atomic_dec, or simply, atomic_set to 0, as implied in the TODO.
=> fixed access variable reset method

tools/labs/qemu/qemu.sh
Add the `--line-buffered` command line argument in the egrep call of the qemu terminal symlink (`serial.pts`) one-liner.
This resolves #31 on my Kubuntu 18.04.
=> Use line buffered egrep in pts symlink one-liner of qemu lab script

Documentation/teaching/labs/introduction.rst
Because we are using virtio the device name is vd* not sd*. Also,
because it is the fourth disk the name will be /dev/vdd.
Signed-off-by: Diana Ungureanu <diana-gabriela.ungureanu@nxp.com>
=> Documentation: labs: Fix mount device name

Documentation/teaching/labs/introduction.rst, tools/labs/templates/kernel_modules/9-dyndbg/dyndbg.c
Course presents F5/F6 keys as shortcuts to move between multiple
results but they are not implemented (not working).
Signed-off-by: Lazar Razvan <grigore.razvan.lazar@gmail.com>
=> Documentation: labs: implement cnext/cprev shortcuts for cscope

Documentation/teaching/labs/kernel_api.rst
=> teaching: kernel_api: Fix typo in structure name

tools/labs/templates/assignments/0-list/list.c
* CONFIG_FRAME_WARN is set to 1024 and we had a warning that a frame
size was larger than this
Signed-off-by: Claudiu Ghioc <claudiu.ghioc@gmail.com>
=> list: update PROCFS_MAX_SIZE to 512

Documentation/teaching/labs/device_drivers.rst
Fix some typos in the lab documentation
=> teaching:labs:device_drivers: fix typos and missing macros

Documentation/teaching/labs/device_drivers.rst
"device" and "my_data->buffer" represent the same thing(dev is
simulated). Add offset in my_write func, like my_read.
=> teaching: labs: device_drivers: Fix my_read/my_write

Documentation/teaching/labs/deferred_work.rst
Timers API changed since 4.14:
* setup_timer was renamed to timer_setup
* timer handlers argument type is now `struct timer_list *`
=> teaching: labs: deferred_work: Timer API changes

Documentation/teaching/labs/interrupts.rst
Check [here](https://ocw.cs.pub.ro/courses/so2/laboratoare/lab05#tratarea_intreruperilor) for the original version.
=> Documentation: teaching: labs: interrupts Fix translation

Documentation/teaching/labs/deferred_work.rst
In order to setup a timer we need to use timer_setup() instead of setup_timer().
=> teaching: labs: deferred_work: Fix content

tools/labs/templates/filesystems/minfs/kernel/minfs.c
* if I_NEW flag is not set after iget_locked then we are dealing with a
cached inode which can be used right away.
Signed-off-by: Claudiu Ghioc <claudiu.ghioc@gmail.com>
=> teaching: labs: filesystems part 2: minfs: return inode from cache

tools/labs/templates/kernel_modules/9-dyndbg/dyndbg.c
Dyndbg can't filter messages printed by pr_info(). Use pr_debug() instead.
=> tools: labs: kernel_modules: fix dyndbg

tools/labs/templates/assignments/3-raid/checker/README
The `README` doesn't say the `run-test` executable must be linked in the current folder. Add this clarification.
=> tools/labs/assignment: Clarify location of scripts for testing 3-raid

tools/labs/qemu/Makefile
As of QEMU 3.0 the vlan parameter has been removed, so I had to change the
-net option to -netdev, which has a similar functionality to vlan, ie run the
device in a separate network.
=> tools: labs: qemu: Makefile: Remove deprecated vlan parameter

README.rst
At some point we renamed Documentation/labs with Documentation/teaching
but did not update README.rst symbolic link. Do it now!
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
=> README: Fix README.rst link

tools/labs/Makefile
Address issue #134 by moving the deletion of the skels directory to another target, and change the clean target to only delete generated files
=> tools/labs: Change make clean rule to only remove generated files

.github/workflows/main.yml
This will enable support for visualizing documentation changes on
linux-kernel-library.github.io.
=> .github: publish CI artifacts to linux-kernel-library.github.io

tools/labs/qemu/create_net.sh
When running as root, the USER variable is not set, so we have to set it
explicitly.
=> tools/labs/qemu: set USER variable explicitly

Documentation/teaching/labs/interrupts.rst
The correct return value for the case when interrupt was not from this device or was not handled is IRQ_NONE.
https://elixir.bootlin.com/linux/latest/source/include/linux/irqreturn.h#L12
=> Fix typo IRQ_NONE

tools/labs/Makefile.vmchecker, tools/labs/scripts/so2-startup-script, tools/labs/scripts/vmchecker-setup
Fix issues in vmchecker scripts and Makefile (`Makefile.vmchecker`):
* the clean slate image is now created from the initial image (not wrongly from the running image)
* create placeholder output files in case they are absent (`run-stdout.vmr` and `run-stderr.vmr`)
* postprocess kernel messages file to only show relevant information
=> Fix setup and assignment cleanup in vmchecker scripts

tools/labs/templates/kernel_api/6-list-sync/list-sync.c
As soon as the lock is unlocked in `task_info_find_pid`,
the caller cannot be sure if the pointer that is returned is valid.
As long as the returned pointer is used, the lock must be held.
In the case of `task_info_add_to_list`, the lock that must be held is a writer lock,
in case of a reader lock other readers could read an inconsistent state of the `struct task_info`.
=> templates: 6-list-sync: Fix potential dangling pointer

Documentation/teaching/labs/block_device_drivers.rst, tools/labs/templates/block_device_drivers/4-5-relay-disk/relay-disk.c
Starting from kernel version 4.10, `bio_set_op_attrs` is marked as
obsolete. The recommended action is to directly assign the `bio_opf`
field of the `struct bio`.
Code extract from `/include/linux/blk_types.h` (v4.19):
```c
/* obsolete, don't use in new code */
static inline void bio_set_op_attrs(struct bio *bio, unsigned op,
unsigned op_flags)
{
bio->bi_opf = op | op_flags;
}
```
Signed-off-by: Horia Ion <horiapaulion@gmail.com>
=> labs: block_device_drivers: Replace obsolete bio_set_op_attrs

tools/labs/templates/filesystems/minfs/kernel/minfs.c
`minfs_write_inode` should fill the disk inode with the aquired `uid` and `gid` from the inode, not the other way round.
Please check the `minix` solution below:
https://elixir.bootlin.com/linux/latest/source/fs/minix/inode.c#L557
=> minfs_write_inode uid/gid issue

.github/workflows/main.yml
This fixes errors during the "Install native dependencies" step for
building documentation.
=> .github: update apt database before installing packages

tools/labs/templates/networking/1-2-netfilter/user/test.c
For the `makedev` macro in newer versions of Glibc (since v2.28) we need
to directly include <sys/sysmacros.h>, because that is no longer
included by <sys/types>.
Fix by including the correct header.
Signed-off-by: Paul-Stelian Olaru <paul_stelian.olaru@stud.acs.upb.ro>
=> labs: networking: Fix includes in userspace component

tools/labs/.gitignore
Up until this commit only `core-image-miminal-*` Yocto image files were ignored.  Others, such as `core-image-sato-*` Yocto image files were not. This commit fixes that, will al Yocto image files being ignored.
=> tools: labs: Ignore all Yocto image files

tools/labs/templates/deferred_work/3-4-5-deferred/user/Makefile, tools/labs/templates/device_drivers/user/Makefile, tools/labs/templates/memory_mapping/test/Makefile
The clean rule failed for some labs because the clean target wasn't defined in all the makefiles. This PR adds it to all the make files.
=> tools/labs: Add clean target to all Makefiles

tools/labs/templates/assignments/5-pitix/checker/_checker
For 5-pitix assignment there is no info about score or the number of test passed (at least a counter). Simple searching for "failed" in output is error prone (and painfully hard for the average Joe).
A simple solution is to add a test_ok var to count the number of passed test. Better solutions exist, but keep it simple stupid as fellow student only care about the number of tests passed to know the homework is okay.
=> [5-PITIX] Add score information in checker

Documentation/teaching/labs/device_drivers.rst
`$` should be used with normal shell commands, while `#` should be used for root commands.
`ls` commands on /dev/* doesn't usually require root access.
=> Documentation: proper use of $ and #

Documentation/teaching/info/contributing.rst
Commit 44b5f01651c4 ("Documentation/teaching: Use 'src/linux' instead of
'so2/linux'") missed fixing directory creation command.  This commit
fixes it.
Signed-off-by: SeongJae Park <sj38.park@gmail.com>
=> Documentation/teaching: Fix remaining '~/so2' in contributing.rst

Documentation/teaching/labs/block_device_drivers.rst
the `inte i;` here clashes with `struct bvec_iter i;` and is not used
=> documentation: removed `inte i` from code block

Documentation/teaching/labs/interrupts.rst
This PR fixes trivial nits in the `interrupts.rst` file.
=> Documentation/teaching/labs/interrupts: Fix nits

tools/labs/qemu/Makefile
As commit 312ee68752fa ("kconfig: announce removal of oldnoconfig if
used") announced, remove oldnoconfig target.
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
=> tools: labs: Remove oldnoconfig target

tools/labs/docker/docs/Dockerfile
Set the DEBIAN_FRONTEND=noninteractive environment variable:
Since we build the docker image, the package system can't prompt the
user for options.
Install the apt-utils package:
This remove the warning messages about package configuration delay.
Install the imagemagick package:
At some point in the documentation generation process, the scripts call
the `convert` command, which is in the imagemagick package. Without it,
`make docker-docs` fails.
Install the packages suggest by the sphinx output:
dvipng python3-venv fonts-noto-cjk latexmk librsvg2-bin texlive-xetex.
=> Fix make docker-docs

tools/labs/templates/kernel_modules/8-kdb/hello_kdb.c
* use proc_ops instead of file_operations
Signed-off-by: Claudiu Ghioc <claudiu.ghioc@gmail.com>
=> labs: kernel_modules: use proc_ops when calling proc_create

Documentation/teaching/so2/lab1-intro.rst
**Issue**:
Sphinx replaces underscores in label names with dashes, hence the reference to the Good to know section from the Note above [Exercises](https://linux-kernel-labs.github.io/refs/heads/master/so2/lab1-intro.html#exercises)  doesn't work.
E.g.
```
File: linux/Documentation/teaching/so2/lab1-intro.rst
.. _good_to_know:
Good to know
============
```
```
File: linux/Documentation/output/teaching/so2/lab1-intro.rst
<div class="section" id="good-to-know">
```
=> Update the <Good to know> label for cross referencing

Documentation/teaching/info/vm.rst
`flex` and `bison` packages are required to build the kernel image.
KVM is not strictly required.
=> Documentation/teaching: Add flex and bison as infrastructure requirements

Documentation/teaching/labs/kernel_api.rst, tools/labs/templates/kernel_api/7-list-test/list-test.c
Functions used in 7-list-test.c are not exported by default, this is only done after solving exercise 6.
Signed-off-by: Valentin Ghita <valx92@gmail.com>
=> labs: kernel_api: fix skel build for kernel_api lab

Documentation/teaching/labs/introduction.rst
Clangd is a language server that facilitates easy navigation and completion
of C code. It think it would be useful to mention it in the code navigation section, given that [support](https://patchwork.kernel.org/project/linux-kbuild/patch/20181206222318.218157-1-tmroeder@google.com/) for it has been added for some time now.
=> Documentation: teaching: Add clangd to code navigation section

tools/labs/templates/kernel_api/3-memory/memory.c
Replace 'text' with 'task' in memory.c.
Delete whitespace in empty line.
=> tools: labs: Fix typos in kernel_api

tools/labs/templates/assignments/0-list/list.c
* proc_create uses proc_ops instead of file_operations
Signed-off-by: Claudiu Ghioc <claudiu.ghioc@gmail.com>
=> assignments: 0-list: use proc_ops instead of file_operations

tools/labs/templates/deferred_work/3-4-5-deferred/kernel/deferred.c
sizeof(p) allocates only the size of pointer, we should use sizeof(*p)
to allocate the size of the structure.
=> 3-4-5-deferred: fix sizeof of pointer allocation

tools/labs/templates/memory_mapping/kmmap/kmmap.c, tools/labs/templates/memory_mapping/vmmap/vmmap.c
`proc_create` API is now using `struct proc_ops` instead of `struct file_operations`.
Signed-off-by: Valentin Ghita <valx92@gmail.com>
=> labs: templates: memory_mapping: change file_operations to proc_ops

tools/labs/templates/device_drivers/kernel/so2_cdev.c
schedule_timeout expect the timeout value in jiffies. To pass the value
in seconds, we need to multiply in by the constant HZ.
Signed-off-by: Wander Lairson Costa <wander.lairson@gmail.com>
=> Fix process sleep in the cdev driver

tools/labs/qemu/Makefile
This enables nested virtualization. Result: Guest vm opens up faster.
=> Add option for nested virtualization in qemu/Makefile

Documentation/teaching/labs/networking.rst
The link appeared to be broken and there was also a typo.
Hope it helps!
=> Documentation: teaching: lectures: fix Beej's link on networking lecture

Documentation/teaching/so2/assign-collaboration.rst, Documentation/teaching/so2/index.rst
This documents serves as a guideline for working inside a team.
It encourages members to use git and PR, work on a common design,
split the work into smaller tasks and then doing peer review.
The final result should be the code together with git history logs.
Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
=> teaching: Add collaboration guideline for SO2 assignments

Documentation/teaching/labs/deferred_work.rst, Documentation/teaching/labs/interrupts.rst, Documentation/teaching/labs/networking.rst, Documentation/teaching/lectures/fs.rst, Documentation/teaching/lectures/interrupts.rst, Documentation/teaching/lectures/memory-management.rst, Documentation/teaching/lectures/processes.rst, tools/labs/templates/interrupts/kbd.c, tools/lib/subcmd/subcmd-util.h
Backport a patch from [Kees Cook](
https://github.com/torvalds/linux/commit/52a9dab6d892763b2a8334a568bd4e2c1a6fde66) that fixes a compilation _error_ on presumably new versions of `gcc` (I got hit by this while running `gcc version 12.2.0 (GCC)`).
And a couple of small fixes.
=> Fix compilation with new gcc versions and other small fixes

tools/labs/qemu/Makefile
Pass pci=noacpi to the kernel command line to work-around and issue where the boot process get stuck while discovering PCI interrupt links:
[    2.846955] ACPI: Power Button [PWRF]
[    9.749737] PCI Interrupt Link [LNKC] enabled at IRQ 11
[   16.426134] PCI Interrupt Link [LNKA] enabled at IRQ 10
[   22.859276] PCI Interrupt Link [LNKB] enabled at IRQ 10
[   28.869926] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:
[   28.869926] 	(detected by 0, t=6502 jiffies, g=-891, q=521853)
[   28.869926] rcu: All QSes seen, last rcu_sched kthread activity 6502 (-67832--74334), jiffies_till_next_fqs=1, root ->qsmask 0x0
[   28.869926] rcu: rcu_sched kthread starved for 6502 jiffies! g-891 f0x2 RCU_GP_WAIT_FQS(5) ->state=0x0 ->cpu=0
[   28.869926] rcu: 	Unless rcu_sched kthread gets sufficient …
=> tools: labs: qemu: use pci=noacpi

Documentation/teaching/labs/networking.rst
first, thanks - the documentation here is quite helpful.
while using it, I came across (a warning)[https://linux-kernel-labs.github.io/refs/heads/master/labs/networking.html#netfilter-1] which worked, so I looked into it and it was changed. (commit 21d1196a35f5686c4323e42a62fdb4b23b0ab4a3),
and I think the documentation here should reflect that too.
=> networking.rst: tcp_hdr restrictions pre 3.11-rc2

Documentation/teaching/labs/block_device_drivers.rst
After freeing the tag set, deleting the queue will result in a page fault.
Therefore the order is:
```
blk_cleanup_queue(dev->queue);
blk_mq_free_tag_set(&dev->tag_set);
```
Signed-off-by: Andrei David <dandrei279@gmail.com>
=> Documentation: Fix Example Causing Page Fault

tools/labs/docker/kernel/Dockerfile, tools/labs/qemu/run-qemu.sh
In this commit, I added a rule to install samba in the docker because it is required by the new setup. And I removed the qemu_kvm variable from the qemu/run-qemu.sh script when kvm is not available (It is easier this way than setting the QEMU_KVM environment variable).
=> Solve `make console` bugs for docker

tools/labs/templates/device_drivers/kernel/so2_cdev.c
This is a simple patch in order to implement the "Remove exclusive access condition from previous exercise" step in solving the extra part for this labs.
I would also like to note, that the folder `tools/labs/templates/device_drivers/extra/char-driver-lin` should be removed.
=> labs/device_drivers: disable exclusive access for extra

Documentation/teaching/labs/arm_kernel_development.rst
I have changed the command that prints the /proc/iomem file.
=> documentation: arm_kernel_development: Fix show iomem command

Documentation/teaching/labs/kernel_api.rst, Documentation/teaching/labs/kernel_modules.rst
- Correct base address of module in kernel oops debugging example
- Reference current file containing description of page fault error code bits
=> Doc/teaching/lab/kernel_modules: Fix typos

Documentation/teaching/labs/memory_mapping.rst
A sentence was redundant in the memory mapping section of the documentation
=> documentation: memory mapping: Remove redundant text

Documentation/teaching/labs/filesystems_part2.rst
https://github.com/linux-kernel-labs/linux/blob/766862ca5a9ae17541541ea0cecac7c8810105b7/Documentation/teaching/labs/filesystems_part2.rst?plain=1#L376-L389
https://github.com/linux-kernel-labs/linux/blob/766862ca5a9ae17541541ea0cecac7c8810105b7/Documentation/teaching/labs/filesystems_part2.rst?plain=1#L432-L436
`minix_link` correspond to `link` in the first snippet, so the `simlink` should be modified to `link` in the second snippet
=> Documentation: filesystems_part2: fix typos

Documentation/teaching/lectures/processes.rst
It seems there is  a mistake, i think it should be "called a task and it is used for both threads and processes. "
=> Documentation: Fix grammar errors in the process section.

tools/labs/docker/docs/Dockerfile
The same issue reported in [#378 ](url).
Fix it by using sphinx_rtd_theme version 1.3.0 in docs/Dockerfile
=> Using old sphnix_rtd_theme package for docker-docs target

Documentation/teaching/lectures/memory-management.rst
According to the context, the word is expected to be "list" rather than "block".
=> Documentation: lectures: memory management: Fix typo

tools/labs/qemu/cleanup-net.sh, tools/labs/qemu/create_net.sh
The default action on Fedora and RHEL-based distributions that use FirewallD is to ban DHCP requests. Instead of telling people to turn off their firewall, I recommend adding the tap interfaces to the FirewallD trusted zone.
This commit adds automatic support to the create_net.sh and cleanup-net.sh scripts that set up the tap interfaces. Due to many distributions using FirewallD these days, I opted for using the following command to check if FirewallD is available:
```bash
if [ -e $(which firewall-cmd) ]; then
sudo firewall-cmd --zone=trusted --change-interface=$device
fi
```
However, we will have to create a better solution for this in the future.
=> Added FirewallD support to scripts

Documentation/teaching/so2/assign2-driver-uart.rst, Documentation/teaching/so2/assign3-software-raid.rst
Update Documentation for Assignment 2 - UART
Update Documentation for Assignment 3 - RAID
=> Documentation: Update Assignment 2 deadline

Documentation/teaching/lectures/address-space.rst
=> Documentation: address-space.rst: fix "pud_offet" typo
